aliases: {}
creation_timestamp: 1774545070340
deployment_job_id: null
deployment_job_state: null
description: ''
last_updated_timestamp: 1774545081452
name: Best Wine Quality Predictor
workspace: default
